### ISSUE TITLE
fast fire glitch

### ISSUE THREAD

**Issue by JUNESYNGOTOFLEX** [s1lentq/ReGameDLL_CS#703]
if you take sg552/aug and hold fire (with scope) you fire speed is slowly than usually, but if you flags ~FL_ONGROUND you fire speed faster than m249, fix please

**Comment by aleeperezz16** [comment]
Is this a bug or it's intended? Conditions are made to take priority on firing when a player isn't on ground.

https://github.com/s1lentq/ReGameDLL_CS/blob/b979b5e84f36dc0eb870f97da670b700756217f1/regamedll/dlls/wpn_shared/wpn_aug.cpp#L81-L96

https://github.com/s1lentq/ReGameDLL_CS/blob/b979b5e84f36dc0eb870f97da670b700756217f1/regamedll/dlls/wpn_shared/wpn_sg552.cpp#L80-L95

**Comment by RauliTop** [comment]
It seems to be a bug because they forget about check FOV at that weapons.

Fixed by this:
```
if (!(m_pPlayer->pev->flags & FL_ONGROUND)) 
{ 
 	if (m_pPlayer->pev->fov == DEFAULT_FOV) 
 	{ 
 	 	AUGFire(0.035 + (0.4 * m_flAccuracy), 0.0825, FALSE); 
 	} 
 	else 
 	{ 
 	 	AUGFire(0.035 + (0.4 * m_flAccuracy), 0.135, FALSE); 
  	}
} 
else if (m_pPlayer->pev->velocity.Length2D() > 140) 
{ 
 	if (m_pPlayer->pev->fov == DEFAULT_FOV) 
 	{ 
 	 	AUGFire(0.035 + (0.7 * m_flAccuracy), 0.0825, FALSE); 
 	} 
 	else 
 	{ 
 	 	AUGFire(0.035 + (0.7 * m_flAccuracy), 0.135, FALSE); 
  	}
} 
else if (m_pPlayer->pev->fov == DEFAULT_FOV) 
{ 
 	AUGFire(0.02 * m_flAccuracy, 0.0825, FALSE); 
} 
else 
{ 
 	AUGFire(0.02 * m_flAccuracy, 0.135, FALSE); 
 }
```

**Comment by RauliTop** [comment]
What do you think @wopox1337?

**Comment by Vaqtincha** [comment]
@RauliTop she's is dead

**Comment by wopox1337** [comment]
At this point, we can't say for sure if this behavior is a bug or if it's designed that way. We could be guided by CSS & CS:GO, but it still doesn't seem right to determine the truth. 

At the same time, I do not see a logical explanation for this behavior. If we keep changing the shared code of weapons for the server side, at some point in time we will get more and more out of sync with the client side (prediction) and this will adversely affect the overall experience of the game for the average player.

I propose to leave this behavior "as is".

**Comment by RauliTop** [comment]
> If we keep changing the shared code of weapons for the server side, at some point in time we will get more and more out of sync with the client side (prediction) and this will adversely affect the overall experience of the game for the average player.
> 
> I propose to leave this behavior "as is".

but https://github.com/s1lentq/ReGameDLL_CS/pull/670 is merged...
